### ISSUE TITLE
Using this wrapper with Objective-C

### ISSUE THREAD

**Issue by OguzErtanAyanlarW** [okta/okta-auth-swift#136]
I checked the issues but could not see any issue regarding to usability of this wrapper on iOS Objective-C based projects. Is it possible to use it on Objective-C projects ?

**Comment by miketraverso** [comment]
i have the same question. The Okta OIDC cocoapod has a -Swift.h file that can be used but unfortunately this project doesn't seem to have that included. 

It would be pretty awesome if there were guidance on how to use this swift cocopod in an older Obj-C project. Thank you!

**Comment by oleggnidets-okta** [comment]
Hi guys,
Thanks for the question. 

Unfortunately, we are not going to provide Obj-C compatibility on this library. There're many reasons so:
1. Maintenance. 
2. Performance fault. 
3. Obj-C support makes some restrictions in using Swift.

Swift became the main language in iOS development. Objective-C is used for narrow purposes.

If you work on older Obj-C project, we suggest you mix Swift and Obj-C. It's a good choice because you may migrate your project to Swift incrementally. 
Apple has [a good documentation](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis) about mixing these two languages. 

I close this issue for now. Please, feel free to reopen, ask additional questions or open a new issue.
